// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.', 
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbR8SwDtGsdVWb1hEtoar-C4szgYLv7M',
    appId: '1:286059918562:android:8d23842191a24bd8199abb',
    messagingSenderId: '286059918562',
    projectId: 'mambo-8a542',
    storageBucket: 'mambo-8a542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR500xzjJvGIgEhkztbjRHMTFPZbip-Z0',
    appId: '1:286059918562:ios:27a8aaf1fcf70cc5199abb',
    messagingSenderId: '286059918562',
    projectId: 'mambo-8a542',
    storageBucket: 'mambo-8a542.appspot.com',
    androidClientId: '286059918562-0ado9q1pfhm5ulbfasj2epfbkph594v1.apps.googleusercontent.com',
    iosClientId: '286059918562-a1qj6lpse3set3gjdu17sqsrjl6sn05j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mambo',
  );

}




